// `.open-next/worker.js` is generated by the OpenNext build.
import openNextWorker from './.open-next/worker.js';

export default {
  fetch: openNextWorker.fetch,

  async scheduled(_event, env, context) {
    if (!env.NOTIFICATION_CRON_SECRET) {
      console.error('NOTIFICATION_CRON_SECRET is missing; unread email jobs were not processed.');
      return;
    }

    const request = new Request('https://worker.internal/api/notifications/process', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env.NOTIFICATION_CRON_SECRET}`,
      },
    });

    context.waitUntil(
      openNextWorker.fetch(request, env, context).then(async (response) => {
        if (!response.ok) {
          console.error('Unread email processor failed:', response.status, await response.text());
        }
      }),
    );
  },
};
